
site_name: learning

nav:
    - tutorials:
      - mkdocs:
        - setup mkdocs: "tutorials/markdown_tutor/setup_and_run_mkdocs.md"
        - mkdocs with django: "tutorials/mkdocs/mkdocs_with_django.md"
      - YAML:
        - yaml practice: "tutorials/yaml/yaml_tutorial.md"
      - markdown:
        - markdown settings: "tutorials/markdown_tutor/how_to_markdown.md"
      - jupyter:
        - jupyter in django: "tutorials/jupyter/setup_jupyter_notebook.md"
      - deploy:
        - deploy django app to hoster.by: "tutorials/deploy/deploy_to_hoster_by.md"
        - deploy django app to heroku: "tutorials/deploy/deploy_to_heroku.md"
        - web server VS app server: "tutorials/deploy/web_vs_app_server.md"
    - python:
      - modules:
        - os: "python/modules/os_module.md"
        - os path: "python/modules/os_path_module.md"
        - sys: "python/modules/sys_module.md"
        - datetime: "python/modules/datetime.md"
      - oop:
        - paradygms:
          - encapsulation: "python/oop/encapsulation.md"
          - inheritance: "python/oop/inheritance.md"
          - polymorphism: "python/oop/polymorphism.md"
        - dunder methods:
          - __self__: "python/oop/dunder_methods/self.md"
    - django:
      - settings:
        - __file__: "django/settings/__file__.md"
        - default: "django/settings/settings_file.md"
        - middleware: "django/settings/middleware.md"
        - core: "django/settings/core_settings.md"
      - models:
        - model types:
          - abstract model: "django/models/model_types/abstract_model.md"
          - related_name in abstract model: "django/models/reference_types/related_name_in_abstract_model.md"
          - multi-table model: "django/models/model_types/multi_table_model.md"
          - proxy model: "django/models/model_types/proxy_model.md"
          - proxy example: "django/models/model_types/proxy_example.md" 
        - reference types:
          - related_name: "django/models/reference_types/related_name.md"
          - generic_foreign_key: "django/models/reference_types/generic_foreign_key.md"
        - Meta:
          - abstract: "django/models/meta/abstract.md" 
          - db_table: "django/models/meta/db_table.md"
          - default_related_name: "django/models/meta/default_related_name.md"
          - verbose_name: "django/models/meta/verbose_name.md"
          - verbose_name_plural: "django/models/meta/verbose_name_plural.md"
        - query set:
          - look ups: "django/models/query_set/look_ups.md"
      - servers:
        - threading pool: "django/servers/threading_pool.md"
        - application servers: "django/servers/python_application_servers.md"
        - simple http server: "django/servers/simple_http_server.md"  
    - rest framework:
      - CRUD overview: "rest_framework/create_crud_rest.md"
    - postgresql:
      - вход: "postgres/psql_enter.md"
      - обзор postgres: "postgres/overview.md"
      - стартовый минимум: "postgres/start_work_with_postgres.md"
      - sql types: "postgres/sql_types.md"
    - mysql:
      - data definition language: "mysql/ddl.md"
      - data manipulaton language: "mysql/dml.md"
      - foreign key: "mysql/foreign_key.md"
      - natural join: "mysql/natural_join.md"
      
    - oop:
      - теория ООП:
        - анализ, проектирование, программирование: "oop/theory/ooa_oop_oop.md"
        - объект: "oop/theory/object.md"
    - unix:
      - tools:
        - tmux: "unix/tools/tmux.md"
    - docker:
      - add user to docker group: "docker/add_user_to_docker_group.md"
      - terminology: "docker/terminology.md"
      - docker way: "docker/docker_way.md"
      - best practice for creating images: "docker/best_practice_for_creating_images.md"
      - volumes: "docker/volumes.md"
# добавить секцию
    - algorithms and data structures:
      - sort_algorithms
      - search_algorithms
      - data structures
       

plugins:
    - search

theme:
    name: windmill
    #name: "material"


dev_addr:
    127.0.0.1:8005
